Layout:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Metrics/LineLength:
  Max: 800
  AllowURI: true
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/MutableConstant:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
