json.partial! "api/v1/consolidated_screening_entries/addresses",
  addresses: entry[:_source][:addresses]
json.(entry[:_source],
  :alt_names,
  :call_sign,
  :entity_number,
  :gross_registered_tonnage,
  :gross_tonnage,
  :ids,
  :name,
  :programs,
  :remarks,
  :sdn_type,
  :source,
  :source_list_url,
  :title,
  :vessel_flag,
  :vessel_owner,
  :vessel_type,
)
