---
- :source_created_at: '2013-12-10'
  :source_updated_at: '2013-12-10'
  :name_spanish: Mercurio - Precipitadores Electrostáticos
  :name_portuguese: Mercúrio - Precipitadores Eletrostáticos
  :name_french: Technologie de recyclage du mercure
  :name_english: Mercury - Electrostatic Precipitators
  :name_chinese: 汞-静电除尘器
  :source_id: 201
  :source: EnvironmentalSolution
  :id: 6d7e8bd0e58f773bd90649ab4281831ca6fb9b9a
- :source_created_at: '2013-11-06'
  :source_updated_at: '2013-11-06'
  :name_spanish: 'Tecnologías Asociadas para el Sistema Nacional de Eliminación de Descargas Contaminantes: Estándares de Tratamiento de Aguas Residuales Secundarios o Avanzados'
  :name_portuguese: 'Tecnologias relacionadas para NPDES: Secundário ou Avançada Tratamento de Águas Residuais Normas'
  :name_french: 'Technologies liées au NPDES : normes de traitement secondaire ou avancé des eaux usées'
  :name_english: 'Related Technologies for NPDES: Secondary or Advanced Wastewater Treatment Standards'
  :name_chinese: NPDES相关技术：二级或高级污水处理标准
  :source_id: 200
  :source: EnvironmentalSolution
  :id: 07cb688c619da4eedc61251a4ada2bfa92d80c82
